# Generated by Django 6.0.5 on 2026-05-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, verbose_name='Расширение файла'),
        ),
    ]
