# Generated by Django 6.0.5 on 2026-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний просмотр'),
        ),
    ]
