# Generated by Django 6.0.5 on 2026-05-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_last_viewed_at_viewhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name_plural': 'История просмотра'},
        ),
    ]
